### ISSUE TITLE
'ultimate-ws' is a CommonJS module

### ISSUE THREAD

**Issue by lichwala** [dimdenGD/ultimate-ws#3]
Hi,
Thank you for your work - it seems to be a great replacement for 'ws' package and extremely fast!

One issue popped up on my side when 'ws' has been replaced by 'ultimate-ws'. From the yarn test console:

```
import { WebSocketServer } from 'ultimate-ws'
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'WebSocketServer' not found. The requested module 'ultimate-ws' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ultimate-ws';
const { WebSocketServer } = pkg;
```

The last receipt works fine of course, but in that case it is not _exact_ replacement when you have to modify the old code.
Is that possible to make it ESM-compatible?

Thank you!

**Comment by lichwala** [comment]
In case you are wondering how to support both CommonJS and ESM, here is an excellent post about that:
[https://evertpot.com/universal-commonjs-esm-typescript-packages/](https://evertpot.com/universal-commonjs-esm-typescript-packages/)

**Comment by dimdenGD** [comment]
ESM is now supported in 1.0.11!

**Comment by lichwala** [comment]
Hmmm... unfortunately there is still some issue...
My frontend application (based on React+Vite) build is failed now:
```
x Build failed in 21.14s
error during build:
RollupError: "createRequire" is not exported by "__vite-browser-external", imported by "node_modules/ultimate-ws/src/index.mjs".
file: /home/pi/monorepo/chrome-extension/web/node_modules/ultimate-ws/src/index.mjs:17:9
15: */
16:
17: import { createRequire } from "module";
             ^
18:
19: const require = createRequire(import.meta.url);
```
I know this package is supposed to be used on the server side (Node), but previously (no code changes in the meantime) 'ws' package built fine.
I guess it's because this 'module' package you use is not available on client side, right?

**Comment by dimdenGD** [comment]
Removed use of `createRequire` in 1.0.12

**Comment by lichwala** [comment]
Thank you for trying, but... unfortunately this time there is another issue, which I guess cannot be simply solved by modifying your source code:
```
Uncaught Error: This version of uWS.js supports only Node.js versions 18, 20, 21 and 22 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

ReferenceError: process is not defined
    at index-DxXGci9q.js:179:3077
    at index-DxXGci9q.js:181:19
```
and I'm trying to build my application on ARM-based machine (namely: Raspberry PI).
Is that possible to include **all** platforms available for Node (and listed in the link above) in underlying uWS library?

The error above comes from the following part of uWS code:
```
uws.exports = ( () => {
    try {
        return commonjsRequire("./uws_" + process.platform + "_" + process.arch + "_" + process.versions.modules + ".node")
    } catch (c) {
        throw new Error(`This version of uWS.js supports only Node.js versions 18, 20, 21 and 22 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

` + c.toString())
    }
}
)();
```
So maybe that's not the platform issue itself, but CommonJS-related ('commonjsRequire' throws) issue again?

**Comment by dimdenGD** [comment]
You can try polyfilling `process`, this isn't an issue with ultimate-ws but with uWebSockets
