### ISSUE TITLE
uWebSockets.js version not kept in sync

### ISSUE THREAD

**Issue by Alaskyh** [dimdenGD/ultimate-ws#4]
`ultimate-ws` has not received an update on the `uWebSockets.js` version it depends on.

As a minor issue, since both `ultimate-express` and `ultimate-ws` specify only one acceptable version, it means two versions are downloaded, which pollute the dependencies of a project.

Unfortunately, since it is not a package that's published to npm, there's no support for semantic versioning, so it means this has to receive an update everytime the uWS.js version changes, or is otherwise changed on `ultimate-express` and a release is made.

**Comment by dimdenGD** [comment]
updated version
